site_name: Accounts Processor Docs
site_description: Документация проекта Trafficgram
site_author: Yaroslav Gladkyi
repo_url: https://github.com/IUDA194/mk-docs-config
repo_name: IUDA194/mk-docs-config

theme:
  name: material
  language: ru
  logo: https://iudalab.cloud/logo.svg
  favicon: https://iudalab.cloud/logo.svg

  palette:
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

  features:
    - navigation.sections      # Группировка как папки
    - navigation.indexes       # README/index как главная страницы папки
    - navigation.prune         # Раскрыт только активный раздел
    - navigation.tracking
    - navigation.top
    - navigation.instant
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Accounts Service:
      - Overview: accounts-service/README.md
      - Methods:
          - accounts.get: accounts-service/get.md
          - accounts.lock: accounts-service/lock.md
          - accounts.release: accounts-service/release.md
      - Upload:
          - accounts.upload.batch: accounts-service/upload-batch.md
          - accounts.upload.single: accounts-service/upload-single.md
